// Copyright 2017-2023 Block, Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/rce.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STATE int32

const (
	STATE_UNKNOWN  STATE = 0
	STATE_PENDING  STATE = 1
	STATE_RUNNING  STATE = 2
	STATE_COMPLETE STATE = 3
	STATE_FAIL     STATE = 4
	STATE_TIMEOUT  STATE = 5
	STATE_STOPPED  STATE = 6
)

// Enum value maps for STATE.
var (
	STATE_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETE",
		4: "FAIL",
		5: "TIMEOUT",
		6: "STOPPED",
	}
	STATE_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"RUNNING":  2,
		"COMPLETE": 3,
		"FAIL":     4,
		"TIMEOUT":  5,
		"STOPPED":  6,
	}
)

func (x STATE) Enum() *STATE {
	p := new(STATE)
	*p = x
	return p
}

func (x STATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_rce_proto_enumTypes[0].Descriptor()
}

func (STATE) Type() protoreflect.EnumType {
	return &file_pb_rce_proto_enumTypes[0]
}

func (x STATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATE.Descriptor instead.
func (STATE) EnumDescriptor() ([]byte, []int) {
	return file_pb_rce_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pb_rce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pb_rce_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	State         STATE                  `protobuf:"varint,3,opt,name=State,proto3,enum=rce.STATE" json:"State,omitempty"`
	PID           int64                  `protobuf:"varint,4,opt,name=PID,proto3" json:"PID,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	StopTime      int64                  `protobuf:"varint,6,opt,name=StopTime,proto3" json:"StopTime,omitempty"`
	ExitCode      int64                  `protobuf:"varint,7,opt,name=ExitCode,proto3" json:"ExitCode,omitempty"`
	Args          []string               `protobuf:"bytes,8,rep,name=Args,proto3" json:"Args,omitempty"`
	Stdout        []string               `protobuf:"bytes,9,rep,name=Stdout,proto3" json:"Stdout,omitempty"`
	Stderr        []string               `protobuf:"bytes,10,rep,name=Stderr,proto3" json:"Stderr,omitempty"`
	Error         string                 `protobuf:"bytes,11,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_pb_rce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_pb_rce_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Status) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Status) GetState() STATE {
	if x != nil {
		return x.State
	}
	return STATE_UNKNOWN
}

func (x *Status) GetPID() int64 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Status) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Status) GetStopTime() int64 {
	if x != nil {
		return x.StopTime
	}
	return 0
}

func (x *Status) GetExitCode() int64 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Status) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Status) GetStdout() []string {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *Status) GetStderr() []string {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_pb_rce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_pb_rce_proto_rawDescGZIP(), []int{2}
}

func (x *ID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Arguments     []string               `protobuf:"bytes,2,rep,name=Arguments,proto3" json:"Arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pb_rce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pb_rce_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

var File_pb_rce_proto protoreflect.FileDescriptor

const file_pb_rce_proto_rawDesc = "" +
	"\n" +
	"\fpb/rce.proto\x12\x03rce\"\a\n" +
	"\x05Empty\"\x90\x02\n" +
	"\x06Status\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\x05State\x18\x03 \x01(\x0e2\n" +
	".rce.STATER\x05State\x12\x10\n" +
	"\x03PID\x18\x04 \x01(\x03R\x03PID\x12\x1c\n" +
	"\tStartTime\x18\x05 \x01(\x03R\tStartTime\x12\x1a\n" +
	"\bStopTime\x18\x06 \x01(\x03R\bStopTime\x12\x1a\n" +
	"\bExitCode\x18\a \x01(\x03R\bExitCode\x12\x12\n" +
	"\x04Args\x18\b \x03(\tR\x04Args\x12\x16\n" +
	"\x06Stdout\x18\t \x03(\tR\x06Stdout\x12\x16\n" +
	"\x06Stderr\x18\n" +
	" \x03(\tR\x06Stderr\x12\x14\n" +
	"\x05Error\x18\v \x01(\tR\x05Error\"\x14\n" +
	"\x02ID\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\";\n" +
	"\aCommand\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tArguments\x18\x02 \x03(\tR\tArguments*`\n" +
	"\x05STATE\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\b\n" +
	"\x04FAIL\x10\x04\x12\v\n" +
	"\aTIMEOUT\x10\x05\x12\v\n" +
	"\aSTOPPED\x10\x062\xdb\x01\n" +
	"\bRCEAgent\x12 \n" +
	"\x05Start\x12\f.rce.Command\x1a\a.rce.ID\"\x00\x12\x1e\n" +
	"\x04Wait\x12\a.rce.ID\x1a\v.rce.Status\"\x00\x12#\n" +
	"\tGetStatus\x12\a.rce.ID\x1a\v.rce.Status\"\x00\x12\x1d\n" +
	"\x04Stop\x12\a.rce.ID\x1a\n" +
	".rce.Empty\"\x00\x12\"\n" +
	"\aRunning\x12\n" +
	".rce.Empty\x1a\a.rce.ID\"\x000\x01\x12%\n" +
	"\x04Exec\x12\f.rce.Command\x1a\v.rce.Status\"\x000\x01B$Z\"github.com/wd-hopkins/rce-agent/pbb\x06proto3"

var (
	file_pb_rce_proto_rawDescOnce sync.Once
	file_pb_rce_proto_rawDescData []byte
)

func file_pb_rce_proto_rawDescGZIP() []byte {
	file_pb_rce_proto_rawDescOnce.Do(func() {
		file_pb_rce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rce_proto_rawDesc), len(file_pb_rce_proto_rawDesc)))
	})
	return file_pb_rce_proto_rawDescData
}

var file_pb_rce_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_rce_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_rce_proto_goTypes = []any{
	(STATE)(0),      // 0: rce.STATE
	(*Empty)(nil),   // 1: rce.Empty
	(*Status)(nil),  // 2: rce.Status
	(*ID)(nil),      // 3: rce.ID
	(*Command)(nil), // 4: rce.Command
}
var file_pb_rce_proto_depIdxs = []int32{
	0, // 0: rce.Status.State:type_name -> rce.STATE
	4, // 1: rce.RCEAgent.Start:input_type -> rce.Command
	3, // 2: rce.RCEAgent.Wait:input_type -> rce.ID
	3, // 3: rce.RCEAgent.GetStatus:input_type -> rce.ID
	3, // 4: rce.RCEAgent.Stop:input_type -> rce.ID
	1, // 5: rce.RCEAgent.Running:input_type -> rce.Empty
	4, // 6: rce.RCEAgent.Exec:input_type -> rce.Command
	3, // 7: rce.RCEAgent.Start:output_type -> rce.ID
	2, // 8: rce.RCEAgent.Wait:output_type -> rce.Status
	2, // 9: rce.RCEAgent.GetStatus:output_type -> rce.Status
	1, // 10: rce.RCEAgent.Stop:output_type -> rce.Empty
	3, // 11: rce.RCEAgent.Running:output_type -> rce.ID
	2, // 12: rce.RCEAgent.Exec:output_type -> rce.Status
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_rce_proto_init() }
func file_pb_rce_proto_init() {
	if File_pb_rce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rce_proto_rawDesc), len(file_pb_rce_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_rce_proto_goTypes,
		DependencyIndexes: file_pb_rce_proto_depIdxs,
		EnumInfos:         file_pb_rce_proto_enumTypes,
		MessageInfos:      file_pb_rce_proto_msgTypes,
	}.Build()
	File_pb_rce_proto = out.File
	file_pb_rce_proto_goTypes = nil
	file_pb_rce_proto_depIdxs = nil
}
